name: base
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - absl-py=1.4.0=pyhd8ed1ab_0
  - aiofiles=22.1.0=pyhd8ed1ab_0
  - aiohttp=3.7.4.post0=py310h6acc77f_1
  - aiosqlite=0.19.0=pyhd8ed1ab_0
  - alembic=1.10.4=pyhd8ed1ab_0
  - altair=4.2.2=pyhd8ed1ab_0
  - anyio=3.6.2=pyhd8ed1ab_0
  - aom=3.5.0=h27087fc_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h5764c6d_3
  - arrow-cpp=11.0.0=ha770c72_5_cpu
  - asttokens=2.2.1=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrs=22.2.0=pyh71513ae_0
  - aws-c-auth=0.6.24=h84a1944_5
  - aws-c-cal=0.5.20=hc60faf5_6
  - aws-c-common=0.8.11=h0b41bf4_0
  - aws-c-compression=0.2.16=h034cb4b_3
  - aws-c-event-stream=0.2.18=h75388cd_6
  - aws-c-http=0.7.4=hf084cc8_2
  - aws-c-io=0.13.17=h10df833_2
  - aws-c-mqtt=0.8.6=hc41645a_6
  - aws-c-s3=0.2.4=h1b8f470_3
  - aws-c-sdkutils=0.1.7=h034cb4b_3
  - aws-checksums=0.1.14=h034cb4b_3
  - aws-crt-cpp=0.19.7=h0073717_7
  - aws-sdk-cpp=1.10.57=h4707e7a_4
  - babel=2.12.1=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - blas=2.116=openblas
  - blas-devel=3.9.0=16_linux64_openblas
  - bleach=6.0.0=pyhd8ed1ab_0
  - blinker=1.6.2=pyhd8ed1ab_0
  - blosc=1.21.3=hafa529b_0
  - bokeh=3.1.0=pyhd8ed1ab_0
  - boltons=23.0.0=pyhd8ed1ab_0
  - bottleneck=1.3.7=py310h0a54255_0
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - brotlipy=0.7.0=py310h5764c6d_1005
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - c-blosc2=2.8.0=hf91038e_1
  - ca-certificates=2022.12.7=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.0=pyhd8ed1ab_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - certipy=0.1.3=py_0
  - cffi=1.15.1=py310h255011f_3
  - cfitsio=4.2.0=hd9d235c_0
  - chardet=4.0.0=py310hff52083_3
  - charls=2.4.1=hcb278e6_0
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.3=pyhd8ed1ab_0
  - conda=23.3.1=py310hff52083_0
  - conda-package-handling=2.0.2=pyh38be061_0
  - conda-package-streaming=0.7.0=pyhd8ed1ab_1
  - configurable-http-proxy=4.5.4=h3b247e2_2
  - contourpy=1.0.7=py310hdf3cbec_0
  - cryptography=40.0.2=py310h34c0648_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=0.29.34=py310heca2aa9_0
  - cytoolz=0.12.0=py310h5764c6d_1
  - dask=2023.4.1=pyhd8ed1ab_0
  - dask-core=2023.4.1=pyhd8ed1ab_0
  - dav1d=1.0.0=h166bdaf_1
  - debugpy=1.6.7=py310heca2aa9_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.6=pyhd8ed1ab_1
  - distributed=2023.4.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - flatbuffers=23.3.3=hcb278e6_0
  - flit-core=3.8.0=pyhd8ed1ab_0
  - fmt=9.1.0=h924138e_0
  - fonttools=4.39.3=py310h1fa729e_0
  - freetype=2.12.1=hca18f0e_1
  - fsspec=2023.4.0=pyh1a96a4e_0
  - gast=0.4.0=pyh9f0ad1d_0
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.1=h0b41bf4_3
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.31=pyhd8ed1ab_0
  - glog=0.6.0=h6f12383_0
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py310h3ec546c_1
  - google-auth=2.17.3=pyh1a96a4e_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - greenlet=2.0.2=py310heca2aa9_0
  - grpcio=1.51.1=py310h4a5735c_1
  - h5py=3.8.0=nompi_py310ha66b2ad_101
  - hdf5=1.14.0=nompi_hb72d44e_103
  - icu=72.1=hcb278e6_0
  - idna=3.4=pyhd8ed1ab_0
  - imagecodecs=2023.1.23=py310h241fb82_2
  - imageio=2.28.0=pyh24c5eb1_0
  - importlib-metadata=6.6.0=pyha770c72_0
  - importlib_metadata=6.6.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - ipykernel=6.22.0=pyh210e3f2_0
  - ipympl=0.9.3=pyhd8ed1ab_0
  - ipython=8.13.1=pyh41d4057_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.6=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonpatch=1.32=pyhd8ed1ab_0
  - jsonpointer=2.0=py_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter-server-mathjax=0.2.6=pyh5bfe37b_1
  - jupyter_client=8.2.0=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py310hff52083_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.5.0=pyhd8ed1ab_0
  - jupyter_server_fileid=0.9.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyter_server_ydoc=0.8.0=pyhd8ed1ab_0
  - jupyter_telemetry=0.1.0=pyhd8ed1ab_1
  - jupyter_ydoc=0.2.3=pyhd8ed1ab_0
  - jupyterhub=4.0.0=pyh2a2186d_0
  - jupyterhub-base=4.0.0=pyh2a2186d_0
  - jupyterlab=3.6.3=pyhd8ed1ab_0
  - jupyterlab-git=0.41.0=pyhd8ed1ab_1
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.22.1=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.7=pyhd8ed1ab_0
  - jxrlib=1.1=h7f98852_2
  - keras=2.11.0=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py310hbf28c38_1
  - krb5=1.20.1=h81ceb04_0
  - lazy_loader=0.2=pyhd8ed1ab_0
  - lcms2=2.15=haa2dc70_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20220623.0=cxx17_h05df665_6
  - libaec=1.0.6=hcb278e6_1
  - libarchive=3.6.2=h3d51595_0
  - libarrow=11.0.0=h2ebd325_5_cpu
  - libavif=0.11.1=h5cdd6b5_0
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcblas=3.9.0=16_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.0.1=h588be90_0
  - libdeflate=1.18=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h28343ad_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=12.2.0=h65d4601_19
  - libgoogle-cloud=2.7.0=h21dfe5b_1
  - libgrpc=1.51.1=h4fad500_1
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.5.1=h0b41bf4_0
  - liblapack=3.9.0=16_linux64_openblas
  - liblapacke=3.9.0=16_linux64_openblas
  - libllvm11=11.1.0=he0ac6c6_5
  - libmamba=1.4.2=hcea66bb_0
  - libmambapy=1.4.2=py310h1428755_0
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=h7f98852_0
  - libnuma=2.0.16=h0b41bf4_1
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libpng=1.6.39=h753d276_0
  - libprotobuf=3.21.12=h3eb15da_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsolv=0.7.23=h3eb15da_0
  - libsqlite=3.40.0=h753d276_1
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libthrift=0.18.0=h5e4af38_0
  - libtiff=4.5.0=ha587672_6
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.44.2=h166bdaf_0
  - libwebp-base=1.3.0=h0b41bf4_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.10.4=hfdac1af_0
  - libzlib=1.2.13=h166bdaf_4
  - libzopfli=1.0.3=h9c3ff4c_0
  - llvm-openmp=16.0.2=h4dfa4b3_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.2=py310h0cfdcf0_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - mako=1.2.4=pyhd8ed1ab_0
  - mamba=1.4.2=py310h51d5547_0
  - mamba_gator=5.2.0=pyhd8ed1ab_0
  - markdown=3.4.3=pyhd8ed1ab_0
  - markupsafe=2.1.2=py310h1fa729e_0
  - matplotlib-base=3.7.1=py310he60537e_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.5=pyhd8ed1ab_0
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.0=hb012696_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msgpack-python=1.0.5=py310hdf3cbec_0
  - multidict=6.0.4=py310h1fa729e_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=0.5.6=pyhb4ecaf3_1
  - nbclient=0.7.4=pyhd8ed1ab_0
  - nbconvert=7.3.1=pyhd8ed1ab_0
  - nbconvert-core=7.3.1=pyhd8ed1ab_0
  - nbconvert-pandoc=7.3.1=pyhd8ed1ab_0
  - nbdime=3.2.1=pyhd8ed1ab_0
  - nbformat=5.8.0=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - networkx=3.1=pyhd8ed1ab_0
  - nodejs=16.19.0=h4abf6b9_1
  - nomkl=1.0=h5ca1d4c_0
  - notebook=6.5.4=pyha770c72_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - numexpr=2.8.4=py310h690d005_100
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openblas=0.3.21=pthreads_h320a7e8_3
  - openjpeg=2.5.0=hfec8fc6_2
  - openpyxl=3.1.2=py310h2372a71_0
  - openssl=3.1.0=hd590300_2
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - orc=1.8.2=hfdbbad2_2
  - packaging=23.1=pyhd8ed1ab_0
  - pamela=1.0.0=py_0
  - pandas=2.0.1=py310h7cbd5c2_0
  - pandoc=2.19.2=h32600fe_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parquet-cpp=1.5.1=2
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.4.0=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.5.0=py310h065c6d2_0
  - pip=23.1.2=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.5.0=pyhd8ed1ab_0
  - pluggy=1.0.0=pyhd8ed1ab_5
  - pooch=1.7.0=pyha770c72_3
  - prometheus_client=0.16.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - protobuf=4.21.12=py310heca2aa9_0
  - psutil=5.9.5=py310h1fa729e_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-cpuinfo=9.0.0=pyhd8ed1ab_0
  - pyarrow=11.0.0=py310h633f555_5_cpu
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.4=py310h5764c6d_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pycurl=7.45.1=py310h60f9ec7_3
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pyopenssl=23.1.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.19.3=py310h1fa729e_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytables=3.8.0=py310hde6a235_1
  - python=3.10.10=he550d4f_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.3=pyhd8ed1ab_0
  - python-flatbuffers=23.1.21=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.10=3_cp310
  - pytz=2023.3=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pywavelets=1.4.1=py310h0a54255_0
  - pyyaml=6.0=py310h5764c6d_5
  - pyzmq=25.0.2=py310h059b190_0
  - re2=2023.02.01=hcb278e6_0
  - readline=8.2=h8228510_1
  - reproc=14.2.4=h0b41bf4_0
  - reproc-cpp=14.2.4=hcb278e6_0
  - requests=2.29.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rsa=4.9=pyhd8ed1ab_0
  - ruamel.yaml=0.17.21=py310h1fa729e_3
  - ruamel.yaml.clib=0.2.7=py310h1fa729e_1
  - s2n=1.3.37=h3358134_0
  - scikit-image=0.20.0=py310h9b08913_1
  - scikit-learn=1.2.2=py310h41b6a48_1
  - scipy=1.10.1=py310h8deb116_0
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - send2trash=1.8.2=pyh41d4057_0
  - setuptools=67.7.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.10=h9fff704_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlalchemy=2.0.11=py310h2372a71_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.13.5=py310hde88566_2
  - sympy=1.11.1=pypyh9d50eac_103
  - tblib=1.7.0=pyhd8ed1ab_0
  - tensorboard=2.11.2=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.1=py310h600f1e7_4
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.11.1=cpu_py310hd1aba9c_0
  - tensorflow-base=2.11.1=cpu_py310h335d60c_0
  - tensorflow-estimator=2.11.1=cpu_py310hfed9998_0
  - termcolor=2.3.0=pyhd8ed1ab_0
  - terminado=0.17.1=pyh41d4057_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tifffile=2023.4.12=pyhd8ed1ab_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.3=py310h1fa729e_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - ucx=1.14.0=h8c404fb_1
  - unicodedata2=15.0.0=py310h5764c6d_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.5.1=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.7=pyhd8ed1ab_0
  - wrapt=1.15.0=py310h1fa729e_0
  - xlrd=2.0.1=pyhd8ed1ab_3
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xyzservices=2023.2.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - y-py=0.5.9=py310h4426083_0
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.7.0=h27087fc_2
  - yarl=1.9.1=py310h2372a71_0
  - ypy-websocket=0.8.2=pyhd8ed1ab_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zfp=1.0.0=h27087fc_3
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zlib-ng=2.0.7=h0b41bf4_0
  - zstandard=0.19.0=py310hdeb6495_1
  - zstd=1.5.2=h3eb15da_6
  - pip:
      - appdirs==1.4.4
      - brax==0.9.4
      - chex==0.1.85
      - contextlib2==21.6.0
      - dm-control==1.0.16
      - dm-env==1.6
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - etils==1.6.0
      - flask==3.0.2
      - flask-cors==4.0.0
      - flax==0.8.0
      - glfw==2.6.5
      - gym==0.26.2
      - gym-notices==0.0.8
      - itsdangerous==2.1.2
      - jax==0.4.23
      - jaxlib==0.4.23+cuda12.cudnn89
      - jaxopt==0.8.3
      - labmaze==1.0.6
      - llvmlite==0.42.0
      - lxml==5.1.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - mediapy==1.2.0
      - ml-collections==0.1.1
      - ml-dtypes==0.3.2
      - mujoco==3.1.1
      - mujoco-mjx==3.1.1
      - numba==0.59.0
      - numpy==1.26.3
      - nvidia-cublas-cu12==12.3.4.1
      - nvidia-cuda-cupti-cu12==12.3.101
      - nvidia-cuda-nvcc-cu12==12.3.107
      - nvidia-cuda-nvrtc-cu12==12.3.107
      - nvidia-cuda-runtime-cu12==12.3.101
      - nvidia-cudnn-cu12==8.9.7.29
      - nvidia-cufft-cu12==11.0.12.1
      - nvidia-cusolver-cu12==11.5.4.101
      - nvidia-cusparse-cu12==12.2.0.103
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - optax==0.1.9
      - orbax-checkpoint==0.5.2
      - pyopengl==3.1.7
      - pytinyrenderer==0.0.14
      - rich==13.7.0
      - sentry-sdk==1.40.0
      - setproctitle==1.3.3
      - tensorboardx==2.6.2.2
      - tensorstore==0.1.53
      - trimesh==4.1.3
      - wandb==0.16.2
      - werkzeug==3.0.1
prefix: /opt/conda
